### ISSUE TITLE
Initial release checklist (1.0.0)

### ISSUE THREAD

**Issue by 43081j** [parse5/parse5-tools#1]
This is just a tracking issue for what needs doing before this is published publically:

* [x] investigate whether `is*` functions should be migrated into parse5 core (or exported if they already exist)
* [x] #3
* [ ] #4
* [x] #5
* [x] split monolithic code up into individual files if needed
* [x] ensure traversal function interfaces are agreed upon and implementation works as expected
* [x] create a migration PR in the lit repo
* [x] create a migration PR in the modernweb repo
* [x] add a CI setup

Most of this will be about compat with google/mw repos as they're the primary users of dom5 these days. There are other consumers (incl myself) but i'd argue we shouldn't try maintain the old interfaces as there will be many unused functions google only ever made use of.

## Possible gaps in parse5

I've had to create these internal functions:

* `isDocument`
* `isDocumentFragment`
* `isTemplateNode`
* `isParentNode`
* `isChildNode`

I feel like most of these should really be part of the tree adapter interface, since thats where the others currently live (e.g. `isTextNode`, `isElementNode`, etc).

cc @fb55 

also @fb55 i can't see the settings of this repo now that i moved it into parse5 org (to be able to make it public eventually). do you know if im just missing a permission? i also want to rename it to just `tools` i think

also would be nice to cc some people into here before it gets published (e.g. some of lit/mw teams) so maybe we need to make it public but just not publish it yet

**Comment by justinfagnani** [comment]
Do you think this could be dual-published with CommonJS and standard modules before 1.0?

I'm trying to use this in the context of a TS Server plugin, which is sync and CommonJ only, so it's much easier to consume CJS modules.

**Comment by 43081j** [comment]
It's possible I think. It's a shame to have to duplicate the published code, though

I wonder if node will ship `require(esm)` soon enough and backported?

Otherwise maybe we just ship a dual package and drop it once the require stuff is widely available

**Comment by fb55** [comment]
require(esm) was shipped with Node 23

**Comment by 43081j** [comment]
Do you know if it'll get backported?

I don't think we can restrict to `>=23`. So many consumers are on the few majors before that 

If it won't soon enough, maybe we could survive with a dual package temporarily and just take the size hit. It's not a huge package so should still be small
